name: waven_compagnon
description: Une application Wiki pour le jeux Waven.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  filter_list: ^1.0.2
  motion_tab_bar_v2: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true  
  assets:
    - images/wavenLogo.png
    - images/heroes/iop/
    - images/heroes/cra/
    - images/heroes/eniripsa/
    - images/heroes/sram/
    - images/heroes/xelor/
    - images/heroes/sacrieur/
    - images/stuffs/
    - images/utils/
    - assets/mockHeroes.json
    - assets/mockCompagnons.json
    - assets/mockStuffs.json
    
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700
